import type { User, Service, Booking, CleanerProfile, Review, Payment } from './types';
export const MOCK_REVIEWS: Review[] = [
    { id: 'r1', bookingId: 'b2', clientId: 'client-1', cleanerId: 'cleaner-1', authorName: 'Tunde Adebayo', rating: 5, comment: "Aisha is fantastic! My apartment has never been cleaner. Highly recommended.", date: "2023-10-15T10:00:00Z", authorAvatarUrl: 'https://api.dicebear.com/8.x/adventurer/svg?seed=Tunde' },
    { id: 'r2', bookingId: 'b3', clientId: 'client-1', cleanerId: 'cleaner-2', authorName: 'Tunde Adebayo', rating: 5, comment: "Professional, punctual, and incredibly thorough. The best cleaning service I've used in Lagos.", date: "2023-10-12T14:30:00Z", authorAvatarUrl: 'https://api.dicebear.com/8.x/adventurer/svg?seed=Tunde' },
];
export const MOCK_SERVICES: Service[] = [
  { id: 's1', cleanerId: 'cleaner-1', name: 'Standard Home Cleaning', description: 'Thorough cleaning of all living areas, kitchen, and bathrooms.', price: 7500, priceUnit: 'flat_rate' },
  { id: 's2', cleanerId: 'cleaner-1', name: 'Deep Cleaning', description: 'Intensive cleaning for a spotless finish, includes inside appliances.', price: 15000, priceUnit: 'flat_rate' },
  { id: 's3', cleanerId: 'cleaner-1', name: 'Office Cleaning', description: 'Keep your workspace productive and professional.', price: 5000, priceUnit: 'per_hour' },
  { id: 's4', cleanerId: 'cleaner-2', name: 'Basic Apartment Clean', description: 'A quick and efficient clean for smaller apartments.', price: 6000, priceUnit: 'flat_rate' },
  { id: 's5', cleanerId: 'cleaner-2', name: 'Move-in/Move-out Clean', description: 'Comprehensive cleaning for empty homes.', price: 20000, priceUnit: 'flat_rate' },
  { id: 's6', cleanerId: 'cleaner-3', name: 'Commercial Space Cleaning', description: 'Tailored cleaning solutions for businesses in Kano.', price: 8000, priceUnit: 'per_hour' },
];
export const MOCK_USERS: (User | CleanerProfile)[] = [
  {
    id: 'client-1',
    name: 'Tunde Adebayo',
    email: 'client@cleanconnect.com',
    role: 'client',
    passwordHash: 'mock_password123',
    avatarUrl: 'https://api.dicebear.com/8.x/adventurer/svg?seed=Tunde',
    idImageUrl: 'https://i.imgur.com/example-id-client.png',
  },
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@cleanconnect.com',
    role: 'admin',
    passwordHash: 'mock_password123',
    avatarUrl: 'https://api.dicebear.com/8.x/initials/svg?seed=Admin',
  },
  {
    id: 'cleaner-1',
    name: 'Aisha Bello',
    email: 'aisha.bello@example.com',
    role: 'cleaner',
    passwordHash: 'mock_password123',
    avatarUrl: 'https://api.dicebear.com/8.x/lorelei/svg?seed=Aisha',
    bio: "With over 5 years of professional cleaning experience, I bring meticulous attention to detail and a passion for creating pristine environments.",
    location: 'Ikeja, Lagos',
    state: 'Lagos',
    city: 'Ikeja',
    rating: 4.9,
    reviewsCount: 88,
    isPremium: true,
    services: MOCK_SERVICES.filter(s => s.cleanerId === 'cleaner-1'),
    cleanerType: 'individual',
    specialties: ["Residential Cleaning", "Deep Cleaning", "Green/Eco-Friendly Cleaning"],
    idImageUrl: 'https://i.imgur.com/example-id.png',
    workGallery: [
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=800',
      'https://images.unsplash.com/photo-1603712725038-92a10cac61eb?q=80&w=800',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=800',
      'https://images.unsplash.com/photo-1527515637462-c2b2b3c02f20?q=80&w=800',
    ],
    subscriptionExpiresAt: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    featuredUntil: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cleaner-2',
    name: 'Chinedu Okoro',
    email: 'chinedu.okoro@example.com',
    role: 'cleaner',
    passwordHash: 'mock_password123',
    avatarUrl: 'https://api.dicebear.com/8.x/lorelei/svg?seed=Chinedu',
    bio: "Reliable and efficient cleaner based in Abuja. I guarantee a sparkling clean home every time.",
    location: 'Abuja, FCT - Abuja',
    state: 'FCT - Abuja',
    city: 'Abuja',
    rating: 4.8,
    reviewsCount: 72,
    isPremium: false,
    services: MOCK_SERVICES.filter(s => s.cleanerId === 'cleaner-2'),
    cleanerType: 'individual',
    specialties: ["Residential Cleaning", "Move-in/Move-out Cleaning"],
    idImageUrl: 'https://i.imgur.com/example-id.png',
    workGallery: [
        'https://images.unsplash.com/photo-1541123437800-1bb1267ab4bc?q=80&w=800',
        'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?q=80&w=800',
    ],
  },
  {
    id: 'cleaner-3',
    name: 'SparklePro Cleaners',
    email: 'fatima.yusuf@example.com',
    role: 'cleaner',
    passwordHash: 'mock_password123',
    avatarUrl: 'https://api.dicebear.com/8.x/lorelei/svg?seed=Fatima',
    bio: "Specializing in commercial and large-scale cleaning projects in Kano. Our team is ready for any challenge.",
    location: 'Kano, Kano',
    state: 'Kano',
    city: 'Kano',
    rating: 4.7,
    reviewsCount: 51,
    isPremium: true,
    services: MOCK_SERVICES.filter(s => s.cleanerId === 'cleaner-3'),
    cleanerType: 'company',
    companyName: 'SparklePro Cleaners Ltd.',
    specialties: ["Commercial/Office Cleaning", "Post-Construction Cleaning", "Event Cleanup"],
    idImageUrl: 'https://i.imgur.com/example-id.png',
    companyRegistrationUrl: 'https://i.imgur.com/example-cac.png',
    workGallery: [
        'https://images.unsplash.com/photo-1596643564238-93e1b6c1454c?q=80&w=800',
        'https://images.unsplash.com/photo-1628177241333-4f1d5d057157?q=80&w=800',
        'https://images.unsplash.com/photo-1585421997802-8b6a1b9a0c3e?q=80&w=800',
    ],
    subscriptionExpiresAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
export const MOCK_BOOKINGS: Booking[] = [
  { id: 'b1', clientId: 'client-1', cleanerId: 'cleaner-1', serviceId: 's1', bookingDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), status: 'confirmed', address: '123 Main St, Ikeja, Lagos', totalCost: 7500 },
  { id: 'b2', clientId: 'client-1', cleanerId: 'cleaner-1', serviceId: 's2', bookingDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), status: 'approved', address: '123 Main St, Ikeja, Lagos', totalCost: 15000, reviewId: 'r1' },
  { id: 'b3', clientId: 'client-1', cleanerId: 'cleaner-2', serviceId: 's4', bookingDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), status: 'approved', address: '456 Broad St, VI, Lagos', totalCost: 6000, reviewId: 'r2' },
  { id: 'b4', clientId: 'client-1', cleanerId: 'cleaner-3', serviceId: 's6', bookingDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), status: 'awaiting_approval', address: '789 Allen Ave, Ikeja, Lagos', totalCost: 8000 },
];
export const MOCK_PAYMENTS: Payment[] = [
  { id: 'p1', cleanerId: 'cleaner-2', cleanerName: 'Chinedu Okoro', amount: 5000, type: 'premium', status: 'pending', createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'p2', cleanerId: 'cleaner-2', cleanerName: 'Chinedu Okoro', amount: 2500, type: 'featured', status: 'pending', createdAt: new Date().toISOString() },
];